query myPortfolioPage($relativePath: String!) {
  portfolioPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
      _values
    }
    ...MyPortfolioPageParts
  }
}

fragment MyPortfolioPageParts on PortfolioPage {
  __typename
  head {
    __typename
    title
    description
  }

  h1
  summary
  linkButtonText
  includesGalleryText
  includesWriteUpText
  includesGalleryAndWriteUpText
}
